{{- range .Values.services }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      containers:
        - name: {{ .name }}
          image: "{{ .image }}:{{ .tag }}"
          ports:
            - containerPort: {{ .port }}
          env:
            - name: EUREKA_INSTANCE_HOSTNAME
              value: "{{ .name }}"
            {{- if ne .name "config-server" }}
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            {{- end }}
            {{- if ne .name "discovery-server" }}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://discovery-server:8761/eureka/"
            {{- end }}
          {{- if .env }}
          {{- range .env }}
            - name: {{ .name }}
              value: "{{ .value }}"
          {{- end }}
          {{- end }}
{{- end }}
